# api/config/api_platform/resources.yaml
resources:
  App\Entity\Person:
    collectionOperations:
      get: ~
      post:
        input: App\DTO\DTOCreateUser
    itemOperations:
      get: ~
      put:
        input: App\DTO\DTOCreateUser
      delete: ~


#  POST/PUT
#
#  donation linked to a user, reward, project
#  user
#  project
#  You have to use ApiPlatform.
