# api/config/api_platform/resources.yaml
App\Entity\Book:
  collectionOperations:
    get: ~ # nothing more to add if we want to keep the default controller
  itemOperations:
    get: ~



## api/config/api_platform/resources.yaml
#resources:
#  App\Entity\Donation:
#    create:
#      method: POST
#      input: App\Entity\Project
#      output: App\Entity\Project
#    put:
#      method: PUT
#      input: App\Entity\Project
#      output: App\Entity\Project
